[package]
org = "ballerinax"
name = "mysql.driver"
version = "1.3.1"
authors = ["Ballerina"]
keywords = ["Azure", "MySQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql.driver"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.26.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mysql.driver-native"
version = "1.3.1"
path = "../native/build/libs/mysql.driver-native-1.3.1-SNAPSHOT.jar"
